use crate::prelude::internal::*;
use relative_path::RelativePath;

impl<LangConfig: GtpLangConfig> GtlConfig<'_, LangConfig> {
    pub(crate) fn render_generated_warning_comment(
        &self,
        target_path: &GtpTargetFilePath,
        source_path: &RelativePath,
        relation: &str,
        comment_prefix: Option<&str>,
    ) -> Result<String, GtlProjectError> {
        let target_dir = target_path.relative_path().parent().ok_or_else(|| {
            GtlProjectError::GenerateTargetFile {
                path: target_path.clone(),
                error: "Failed to resolve the target file parent directory".into(),
            }
        })?;
        let source_path = target_dir.relative(source_path);
        let comment = |content: &str| match comment_prefix {
            Some(prefix) => format!("{prefix} {content}"),
            None => self.lang_config().comment_line(content),
        };
        Ok(format!(
            "{}\n{}",
            comment(&format!(
                "Do not edit manually! The code is generated by `gt init` {relation} {source_path}"
            )),
            comment(r#"Use "genotype" agent skill if available."#),
        ))
    }

    pub(crate) fn render_extra_file_warning_comments(
        &self,
        dist: &mut GtlDist,
    ) -> Result<(), GtlProjectError> {
        if !self.warning_comment() {
            return Ok(());
        }
        for file in &mut dist.files {
            let GtlDistFile::Generated(file) = file else {
                continue;
            };
            if file.source_module_id.is_some() {
                continue;
            }
            let path = file.path.relative_path();
            let prefix = match (path.file_name(), path.extension()) {
                (Some(".gitignore"), _) | (_, Some("toml" | "py")) => "#",
                (_, Some("rs" | "ts")) => "//",
                _ => continue,
            };
            let warning = self.render_generated_warning_comment(
                &file.path,
                self.project_paths().config_file.relative_path(),
                "via",
                Some(prefix),
            )?;
            file.source_code =
                GtpSourceCode::new(format!("{warning}\n\n{}", file.source_code.content));
        }
        Ok(())
    }
}
