[src]
config_hash = "9721834640ff8b48"

[src.modules."types/diagnostic.type"]
id = "diagnostic"
hash = "af1832d5b99ae79c"
deps = []

[src.modules."types/module_id.type"]
id = "module_id"
hash = "db3903852e508778"
deps = []

[dist.ts."../npm-genotype-types/src/core/diagnostic.ts"]
hash = "88ee1177a8ce42f5"
srcId = "diagnostic"

[dist.ts."../npm-genotype-types/src/core/index.ts"]
hash = "b9e37c895686a867"

[dist.ts."../npm-genotype-types/src/core/module_id.ts"]
hash = "d3f2ab0e500b8cd4"
srcId = "module_id"

[dist.rs."src/types/diagnostic.rs"]
hash = "cd625a408b500b2c"
srcId = "diagnostic"

[dist.rs."src/types/mod.rs"]
hash = "884b07eab33cb39c"

[dist.rs."src/types/module_id.rs"]
hash = "539de3964f63f323"
srcId = "module_id"
