[tasks."gen/types"]
description = "Generates core Genotype types for TypeScript and Rust"
run = { task = "//:dev/gt", args = ["build", "pkgs/crate-genotype-core"] }

[tasks."gen/types:watch"]
description = "Generates core Genotype types for TypeScript and Rust in watch mode"
run = { task = "//:dev/gt:watch", args = [
  "pkgs/crate-genotype-core/types",
  "build",
  "pkgs/crate-genotype-core",
] }
