[package]
name = "genotype_lang_ts_project"
version = "0.14.0"
edition = "2024"
description = "Genotype language TypeScript target project crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dependencies]
genotype_parser = { version = "0.14.0", path = "../../../parser" }
genotype_path = { version = "0.14.0", path = "../../../path" }
genotype_config = { version = "0.14.0", path = "../../../config" }
genotype_project = { version = "0.14.0", path = "../../../project" }
genotype_lang_core_tree = { version = "0.14.0", path = "../../core/tree" }
genotype_lang_core_config = { version = "0.14.0", path = "../../core/config" }
genotype_lang_core_project = { version = "0.14.0", path = "../../core/project" }
genotype_lang_ts_tree = { version = "0.14.0", path = "../tree" }
genotype_lang_ts_config = { version = "0.14.0", path = "../config" }
toml_edit = { version = "0.22.26", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
miette = "7.2.0"
thiserror = "1.0.64"

[dev-dependencies]
pretty_assertions = "1.4.1"
