[package]
name = "genotype_lang_ts_project"
version = "0.8.0"
edition = "2021"
description = "Genotype language TypeScript target project crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dependencies]
genotype_parser = { version = "0.8.0", path = "../../../parser" }
genotype_project = { version = "0.8.0", path = "../../../project" }
genotype_config = { version = "0.8.0", path = "../../../config" }
genotype_lang_core_tree = { version = "0.8.0", path = "../../core/tree" }
genotype_lang_core_project = { version = "0.8.0", path = "../../core/project" }
genotype_lang_ts_tree = { version = "0.8.0", path = "../tree" }
genotype_lang_ts_converter = { version = "0.8.0", path = "../converter" }
genotype_lang_ts_config = { version = "0.8.0", path = "../config" }
toml = "0.8.19"
serde = "1.0.210"
serde_json = "1.0.132"
miette = "7.2.0"
thiserror = "1.0.64"

[dev-dependencies]
pretty_assertions = "1.4.1"
genotype_parser = { path = "../../../parser" }
