[package]
name = "genotype_lang_ts_project"
version = "0.1.0"
edition = "2021"

[dependencies]
genotype_parser = { path = "../../../parser" }
genotype_project = { path = "../../../project" }
genotype_lang_core_tree = { path = "../../core/tree" }
genotype_lang_core_project = { path = "../../core/project" }
genotype_lang_ts_tree = { path = "../tree" }
genotype_lang_ts_converter = { path = "../converter" }

[dev-dependencies]
pretty_assertions = "1.4.1"
genotype_parser = { path = "../../../parser" }
