[package]
name = "genotype_lang_ts_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
genotype_parser = { path = "../../../parser" }
genotype_lang_core_parser = { path = "../../core/parser" }
genotype_lang_ts_tree = { path = "../tree" }

[dev-dependencies]
pretty_assertions = "1.4.1"
