[package]
name = "genotype_lang_ts_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
genotype_parser = { path = "../../../parser" }
genotype_lang_core = { path = "../../core" }

[dev-dependencies]
pretty_assertions = "1.4.1"
