name = "genotype-json-schema"

[ts]
enabled = true

[ts.package]
name = "genotype-json-schema"
version = "0.1.0"
description = "Genotype JSON schema"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
files = ["src", "README.md"]

[rust]
enabled = true

[rust.package]
name = "genotype_json_schema"
version = "0.1.0"
edition = "2021"
description = "Genotype JSON schema"
license = "MIT"

[python]
enabled = true
module = "genotype_json_schema"

[python.package]
name = "genotype-json-schema"
version = "0.1.0"
description = "Genotype JSON schema"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
readme = "README.md"
