[workspace]
resolver = "2"
members = [
  "lang/core/tree",
  "lang/core/converter",
  "lang/core/project",
  "lang/ts/tree",
  "lang/ts/converter",
  "lang/ts/project",
  "parser",
  "project",
  "visitor",
]
