[workspace]
resolver = "2"
members = [
  "lang/core/tree",
  "lang/core/converter",
  "lang/core/project",
  "lang/ts/tree",
  "lang/ts/converter",
  "lang/ts/project",
  "lang/py/tree",
  "lang/py/converter",
  # "lang/ts/project",
  "parser",
  "project",
  "visitor",
  "writer",
  "cli",
]
