[changelog]
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro group_section(label, commits) %}
  ### {{ label }}
  {% for commit in commits %}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif -%}
      {% if commit.breaking %}[**breaking**] {% endif -%}
      {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
  {% endfor %}
{% endmacro %}

{%- if version %}
  ## {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
  ## Unreleased
{% endif %}

{%- set_global has_internal_groups = false -%}
{%- for group, commits in commits | group_by(attribute="group") -%}
  {%- set group_label = group | striptags | trim | upper_first -%}

  {%- if group_label != "Chores" and group_label != "Refactors" -%}
    {{ self::group_section(label=group_label, commits=commits) }}
  {%- else -%}
    {% set_global has_internal_groups = true %}
  {%- endif -%}
{%- endfor -%}

{%- if has_internal_groups -%}
<details>

<summary>Show internal changes</summary>
{%  for group, commits in commits | group_by(attribute="group") -%}
  {%- set group_label = group | striptags | trim | upper_first -%}

  {%- if group_label == "Chores" or group_label == "Refactors" -%}
    {{ self::group_section(label=group_label, commits=commits) }}
  {%- endif -%}
{%- endfor %}
</details>
{% endif %}
"""
trim = true
render_always = true
postprocessors = [{ pattern = '<REPO>', replace = "https://github.com/kossnocorp/genotype" }]

[git]
conventional_commits = true
filter_unconventional = true
commit_preprocessors = [{ pattern = '#([0-9]+)', replace = "[#${1}](<REPO>/issues/${1})" }]
commit_parsers = [
  { message = "^feat(.+)?!?:", group = "<!-- 0 --> Features" },
  { message = "^fix(.+)?!?:", group = "<!-- 1 --> Bug Fixes" },
  { message = "^doc(.+)?!?:", group = "<!-- 3 --> Documentation" },
  { message = "^perf(.+)?!?:", group = "<!-- 4 --> Performance" },
  { message = "^chore(.+)?!?:", group = "<!-- 5 --> Chores" },
  { message = "^refactor(.+)?!?:", group = "<!-- 6 --> Refactors" },
]
topo_order_commits = true
sort_commits = "oldest"

[remote.github]
owner = "kossnocorp"
repo = "genotype"
