experimental_monorepo_root = true
[monorepo]
config_roots = ["pkgs/*"]

[tools]
# Stack
# Rust
rust = { version = "latest", channel = "stable", components = "rustfmt,clippy" }
# Node.js
node = "lts"
pnpm = "latest"
oxfmt = "latest"
# Python
python = "3.14.4"
uv = "latest"
ty = "latest"
ruff = "latest"

# Tools
cargo-binstall = "latest"
"cargo:just" = "latest"
"cargo:toml2json" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-release" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:just-lsp" = "latest"
watchexec = "latest"
shfmt = "latest"
gh = "latest"
git-cliff = "latest"
fnox = "latest"
jaq = "latest"

[settings]
lockfile = true
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["rust"] # Use rust-toolchain.toml

[env]
_.file = "./.env"
_.python.venv = { create = true, path = '.venv' }
MISE_EXPERIMENTAL = true # Enable monorepo root support

[tasks.install]
depends = ["install/pnpm", "install/uv"]

[tasks."install/pnpm"]
run = "pnpm install"

[tasks."install/uv"]
run = "uv sync"

[tasks.build]
run = "cargo build"

[tasks.lint]
depends = [
  "lint/rust",
  # TODO: Add JS/Python linters
]

[tasks."lint:fix"]
depends = [
  "lint/rust:fix",
  # TODO: Add JS/Python linters
]

[tasks."lint:watch"]
depends = [
  "lint/rust:watch",
  # TODO: Add JS/Python linters
]

[tasks."lint/rust"]
run = "cargo clippy --all-targets --all-features"

[tasks."lint/rust:fix"]
run = "cargo clippy --all-targets --all-features --fix"
depends_post = "format/rust"

[tasks."lint/rust:watch"]
run = "watchexec -e rs,Cargo.toml,Cargo.lock -rc reset -- cargo clippy --all-targets --all-features"

[tasks.format]
depends = [
  "format/rust",
  # TODO: Add JS/Python formatters
]

[tasks."format:check"]
depends = [
  "format/rust:check",
  # TODO: Add JS/Python formatters
]

[tasks."format/rust"]
run = "cargo fmt --all"

[tasks."format/rust:check"]
run = "cargo fmt --all --check"

[tasks."test/unit"]
depends = [
  "test/unit/rust",
  # TODO: Add JS/Python unit tests
]

[tasks."test/unit:watch"]
depends = [
  "test/unit/rust:watch",
  # TODO: Add JS/Python unit tests
]

[tasks."test/unit/rust"]
run = "cargo nextest run --no-fail-fast"

[tasks."test/unit/rust:watch"]
run = "watchexec -e rs,Cargo.toml,Cargo.lock -rc reset -- cargo nextest run --no-fail-fast"

[tasks."test/system"]
depends = [
  "test/system/examples",
  # TODO: Add more system tests
]

[tasks."test/system/examples"]
run = "./scripts/test-examples.sh"

[tasks.publish]
run = [{ task = "publish/cargo" }]

[tasks."publish/cargo"]
run = '''
cargo release publish \
  --exclude litty \
  --exclude litty_macro \
  --exclude litty_macro_tests \
  --exclude toml_ext \
  --exclude genotype_runtime \
  --exclude genotype_json_types \
  --exclude genotype_test \
  --workspace \
  --all-features \
  --no-verify \
  --no-confirm \
  --allow-branch '*' \
  --execute
'''

[tasks."publish/cargo:dry"]
run = '''
cargo release publish \
  --exclude litty \
  --exclude litty_macro \
  --exclude litty_macro_tests \
  --exclude toml_ext \
  --exclude genotype_runtime \
  --exclude genotype_json_types \
  --exclude genotype_test \
  --workspace \
  --all-features \
  --no-verify \
  --no-confirm \
  --allow-branch '*'
'''

[tasks."version/cargo"]
usage = '''
arg "<version>" help="Version to apply"
'''
run = '''
cargo release version {{usage.version}} \
  --workspace \
  --exclude litty \
  --exclude litty_macro \
  --exclude litty_macro_tests \
  --exclude toml_ext \
  --exclude genotype_runtime \
  --exclude genotype_json_types \
  --no-confirm \
  --execute
'''

[tasks."publish/cargo/litty"]
run = '''
cargo release publish \
  --package litty \
  --package litty_macro \
  --all-features \
  --no-verify \
  --no-confirm \
  --allow-branch '*' \
  --execute
'''

[tasks."publish/cargo/litty:dry"]
run = '''
cargo release publish \
  --package litty \
  --package litty_macro \
  --all-features \
  --no-verify \
  --no-confirm \
  --allow-branch '*'
'''
