[tools]
# Stack
rust = { version = "latest", channel = "stable", components = "rustfmt,clippy" }
node = "lts"
pnpm = "latest"
python = "latest"
uv = "latest"

# Tools
cargo-binstall = "latest"
"cargo:just" = "latest"
"cargo:toml2json" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-release" = "latest"
"cargo:cargo-insta" = "latest"
"cargo:just-lsp" = "latest"
watchexec = "latest"
opencode = "latest"
oxfmt = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["rust"] # Use rust-toolchain.toml

[env]
_.file = "./.env"
