packages:
  - "pkgs/app-website"
  - "pkgs/crate-genotype-lsp"
  - "pkgs/crate-genotype-lsp/npm/*"
  - "pkgs/npm-genotype-tm-grammar"
  - "pkgs/npm-vscode-genotype"
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  sharp: true
  workerd: true
