[package]
name = "genotype_lang_ts_tree"
version = "0.13.0"
edition = "2021"
description = "Genotype language TypeScript target AST crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dependencies]
genotype_parser = { version = "0.13.0", path = "../../../parser" }
genotype_lang_core_tree = { version = "0.13.0", path = "../../core/tree" }
heck = "0.5.0"
miette = "7.2.0"
thiserror = "1.0.64"

[dev-dependencies]
pretty_assertions = "1.4.1"
