package = false
src = "./types/"
dist = "."

[build]
file = false

[ts]
enabled = true
dist = "./ts/src/types/"

[rs]
enabled = true
dist = "./rs/src/types/"

[py]
enabled = true
dist = "./py/module/types/"
