[package]
name = "genotype_lang_ts_config"
version = "0.5.0"
edition = "2021"
description = "Genotype language TypeScript target config crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dev-dependencies]
pretty_assertions = "1.4.1"

[dependencies]
toml = "0.8.19"
