compatibility_date = "2026-04-09"
compatibility_flags = [ "global_fetch_strictly_public", "nodejs_compat" ]
name = "genotype-website"
main = "@astrojs/cloudflare/entrypoints/server"

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true
