module = { SOI ~ (module_doc)* ~ (import | alias)* ~ EOI }

// Base

name = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }

reference = ${ name ~ ((WHITESPACE | COMMENT)* ~ generic_arguments)? }

// Aliases

alias = { annotation* ~ name ~ generic_parameters? ~ ":" ~ descriptors }

// Descriptors

descriptors = @{
    ("|" ~ (WHITESPACE | COMMENT)*)?
    ~ descriptor
    ~ ((WHITESPACE | COMMENT)* ~ "|" ~ (WHITESPACE | COMMENT)* ~ descriptor)*
    ~ ((WHITESPACE | COMMENT)* ~ "|")?
}

descriptor = !{ annotation* ~ descriptor_inner }

// NOTE: Order matters! Prefer structural containers before inline imports
// to avoid ambiguity when parsing nested descriptors (e.g. arrays).
descriptor_inner = _{ literal | primitive | branded | any | object | array | tuple | record | inline_import | alias | reference }

primitive = { primitive_index | "boolean" }

primitive_index = ${ "string" | primitive_numeric }

primitive_numeric = ${ "number" | "int" | "i8" | "i16" | "i32" | "i64" | "i128" | "isize" | "u8" | "u16" | "u32" | "u64" | "u128" | "usize" | "float" | "f32" | "f64" }

any = { "any" }

// Literals

literal = { literal_string | literal_float | literal_integer | literal_boolean | literal_null }

literal_string = ${ quote ~ string_inner ~ quote }

quote = _{ "\"" }

string_inner = @{ (!("\"" | "\\") ~ ANY)* ~ (string_escape ~ string_inner)? }

string_escape  = @{ "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t" | string_unicode) }

string_unicode = @{ "u" ~ ASCII_HEX_DIGIT{4} }

literal_integer = @{ ("+" | "-")? ~ integer }

literal_float = @{ ("+" | "-")? ~ integer ~ ("." ~ digits ~ exponent? | exponent) }

literal_null = ${ "null" }

integer =  @{ "0" | (ASCII_NONZERO_DIGIT ~ digits?) }

digits = @{ (ASCII_DIGIT | ("_" ~ ASCII_DIGIT))+ }

exponent = @{ ("E" | "e") ~ ("+" | "-")? ~ ASCII_DIGIT+ }

literal_boolean = ${ "true" | "false" }

// Branded

branded = ${ "@" ~ primitive }

// Objects

object = { "{" ~ properties? ~ "}" }

properties = ${
    property
    ~ ((WHITESPACE | COMMENT)* ~ "," ~ (WHITESPACE | COMMENT)* ~ property)*
    ~ ((WHITESPACE | COMMENT)* ~ ",")?
}

property = !{ extension_property | optional_property | required_property }

extension_property = ${ "..." ~ (inline_import | reference) }

required_property = { annotation* ~ name ~ ":" ~ descriptors }

optional_property = { annotation* ~ name ~ "?:" ~ descriptors }

// Generics

generic_parameters = { "<" ~ name ~ ("," ~ name)* ~ ">" }

generic_arguments = @{
    "<" ~
    (WHITESPACE | COMMENT)*
    ~ descriptors
    ~ ((WHITESPACE | COMMENT)* ~ "," ~ (WHITESPACE | COMMENT)* ~ descriptors)*
    ~ (WHITESPACE | COMMENT)*
    ~ ">"
}

// Attributes

attribute = { "#[" ~ name ~ attribute_descriptor? ~ "]" }

attribute_descriptor = { attribute_assignment | attribute_arguments | attribute_properties }

attribute_assignment = { "=" ~ attribute_value }

attribute_arguments = { "(" ~ (attribute_value ~ ("," ~ attribute_value)*)? ~ ")" }

attribute_properties = { "(" ~ attribute_property ~ ("," ~ attribute_property)* ~ ")" }

attribute_property = { name ~ "=" ~ attribute_value }

attribute_value = !{ literal | name }

// Annotations

annotation = _{ attribute | line_doc }

// Arrays

array = { "[" ~ descriptors ~ "]" }

// Tuples

tuple = { "(" ~ (descriptors ~ ("," ~ descriptors)*)? ~ ")" }

// Records

record = { "{" ~ record_key ~ ":" ~ descriptors ~ "}" }

record_key = { "[" ~ primitive_index? ~ "]" }

// Modules

import = { "use" ~ import_reference }

import_reference = ${ path ~ (import_glob | import_names | name) }

import_names = !{ "{" ~ (import_name ~ ("," ~ import_name)*)? ~ "}" }

import_name = { name ~ ("as" ~ name)? }

import_glob = ${ "*" }

inline_import = @{ path ~ reference }

path = @{ path_segment+ }

path_segment = ${ "../" | "./" | ((!"/" ~ !NEWLINE ~ !"<" ~ ANY)+ ~ "/") }

// Comments

line_comment = _{ ("//" ~ !("/" | "!") ~ (!NEWLINE ~ ANY)*) }

block_comment = _{ "/*" ~ (block_comment | !"*/" ~ ANY)* ~ "*/" }

module_doc = ${ "//!" ~ SPACE? ~ doc }

line_doc = ${ "///" ~ SPACE? ~ doc }

doc = @{ (!NEWLINE ~ ANY)* }

// Base

SPACE = _{ " " | "\t" }

WHITESPACE = _{ SPACE | NEWLINE }

COMMENT = _{ line_comment | block_comment }
