name = "genotype-test-literal-fields"
dist = "dist"

[ts]
enabled = true

[ts.manifest]
name = "genotype-test-literal-fields-types"
version = "0.1.0"

[rs]
enabled = true

[rs.manifest.package]
name = "genotype_test_literal_fields_types"
version = "0.1.0"
edition = "2024"
