name = "genotype-test-literal-fields"
dist = "dist/ts-effect"

[build]
file = false

[ts]
enabled = true
mode = "effect"

[ts.manifest]
name = "genotype-test-literal-fields-effect-types"
version = "0.1.0"
