src = "./types/"
dist = "."
package = false
formatters = [{ kind = "oxfmt", via = "pnpm" }]

[ts]
enabled = true
mode = "zod"
dist = "../npm-genotype-types/src/project/"

[rs]
enabled = true
dist = "./src/types/"
formatters = [{ kind = "cargo", cmd = "fmt", args = ["--all"] }]
