[tasks.build]
description = "Builds the Wasm package"
usage = '''
flag "--dev" help="Builds in dev mode"
'''
run = '''
#!/usr/bin/env bash

pkg_path="../npm-genotype-wasm"
pkg_json_path="$pkg_path/package.json"
pkg_json_tmp_path="$pkg_json_path.tmp"

assets_path="./assets"

build_args=()
if [ "${usage_dev:-false}" = "true" ]; then
  build_args+=(--dev)
fi

# Build with wasm-pack
wasm-pack build . \
  "${build_args[@]}" \
  --target web \
  --out-dir "$pkg_path" \
  --out-name genotype_wasm

# Assign name in package.json to @genotype-lang/wasm
jaq \
  -e '.name = "@genotype-lang/wasm"' \
  < "$pkg_json_path" \
  > "$pkg_json_tmp_path"
mv "$pkg_json_tmp_path" "$pkg_json_path"

# Copy assets
cp "$assets_path/README.md" "$pkg_path"
'''

[tasks."build:dev"]
description = "Builds the Wasm package in dev mode"
run = [{ task = "build", args = ["--dev"] }]
