// Generated by pkgs/npm-genotype-skill/src/generate-skill.ts.

#[rustfmt::skip]
pub(super) const FILES: &[(&str, &str)] = &[
    ("SKILL.md", include_str!("../../../skill/SKILL.md")),
    ("getting-started.md", include_str!("../../../skill/getting-started.md")),
    ("language.md", include_str!("../../../skill/language.md")),
    ("cli.md", include_str!("../../../skill/cli.md")),
    ("configuration.md", include_str!("../../../skill/configuration.md")),
    ("python.md", include_str!("../../../skill/python.md")),
    ("python-configuration.md", include_str!("../../../skill/python-configuration.md")),
    ("rust.md", include_str!("../../../skill/rust.md")),
    ("rust-configuration.md", include_str!("../../../skill/rust-configuration.md")),
    ("typescript.md", include_str!("../../../skill/typescript.md")),
    ("typescript-configuration.md", include_str!("../../../skill/typescript-configuration.md")),
];
