[package]
name = "genotype_lang_rs_project"
version = "0.9.0"
edition = "2021"
description = "Genotype language Rust target project crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dependencies]
genotype_parser = { version = "0.9.0", path = "../../../parser" }
genotype_project = { version = "0.9.0", path = "../../../project" }
genotype_config = { version = "0.9.0", path = "../../../config" }
genotype_lang_core_tree = { version = "0.9.0", path = "../../core/tree" }
genotype_lang_core_project = { version = "0.9.0", path = "../../core/project" }
genotype_lang_rs_tree = { version = "0.9.0", path = "../tree" }
genotype_lang_rs_converter = { version = "0.9.0", path = "../converter" }
genotype_lang_rs_config = { version = "0.9.0", path = "../config" }
genotype_lang_rs_visitor = { version = "0.9.0", path = "../visitor" }
miette = "7.2.0"
thiserror = "1.0.64"
indexmap = "2.6.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
