[package]
name = "genotype_lang_ts_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
genotype_parser = { path = "../../../parser" }
genotype_lang_core_converter = { path = "../../core/converter" }
genotype_lang_ts_tree = { path = "../tree" }

[dev-dependencies]
pretty_assertions = "1.4.1"
