[package]
name = "genotype_lang_ts_converter"
version = "0.4.0"
edition = "2021"
description = "Genotype language TypeScript target converter crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dependencies]
genotype_parser = { version = "0.4.0", path = "../../../parser" }
genotype_lang_ts_tree = { version = "0.4.0", path = "../tree" }

[dev-dependencies]
miette = "7.2.0"
pretty_assertions = "1.4.1"
