[package]
name = "litty"
version = "0.2.0"
edition = "2024"
description = "Literals for Rust"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dev-dependencies]
pretty_assertions = "1.4.1"
serde_json = "1.0.132"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
litty_macro = { version = "0.2.0", path = "../litty_macro" }
