[package]
name = "genotype_project"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
genotype_parser = { path = "../parser" }
glob = "0.3.1"
num_cpus = "1.16.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
