[package]
name = "genotype_project"
version = "0.1.0"
edition = "2021"
description = "Genotype language project crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dependencies]
genotype_parser = { version = "0.1.1", path = "../parser" }
glob = "0.3.1"
miette = { version = "7.2.0", features = ["fancy"] }
num_cpus = "1.16.0"
rayon = "1.10.0"
thiserror = "1.0.64"

[dev-dependencies]
pretty_assertions = "1.4.1"
