use crate::*;

/// Codegen result resolve. It contains the relevant information to embed the generated code.
#[derive(Debug, PartialEq)]
pub struct GtlCodegenResolve<'a, RenderContext> {
    /// Imports generated by the input node.
    pub imports: Vec<Box<dyn GtlCodegenImport<'a, RenderContext = RenderContext>>>,
    /// Names claimed by the input node.
    pub claims: Vec<String>,
}
