name: Save Target Cache

inputs:
  target-key:
    required: true
    description: "Key for caching target directory."

runs:
  using: "composite"

  steps:
    - name: Save Target Cache
      uses: actions/cache/save@v5
      with:
        path: target
        key: target-${{ runner.os }}-${{ inputs.target-key }}
