name: Save Target Cache
description: "Save cache for the target directory."

inputs:
  target-key:
    required: true
    description: "Key for caching target directory."

runs:
  using: "composite"

  steps:
    - name: Lookup Target Cache
      id: lookup-target
      uses: actions/cache/restore@v5
      with:
        path: target
        key: target-${{ runner.os }}-${{ inputs.target-key }}-${{ github.sha }}
        lookup-only: true

    - name: Save Target Cache
      if: ${{ steps.lookup-target.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v5
      with:
        path: target
        key: target-${{ runner.os }}-${{ inputs.target-key }}-${{ github.sha }}
