install:
  cargo install toml2json

build: build-syntax build-extension

build-syntax:
  toml2json ./src/syntax.toml --pretty > ./syntaxes/genotype.tmLanguage.json

build-extension:
  pnpm exec tsc

build-extension-watch:
  pnpm exec tsc --watch

version version:
  npm version {{version}}
  cd client && npm version {{version}}
  cd server && npm version {{version}}

publish: build
	npx @vscode/vsce publish