[tools]
ffmpeg = "latest" # Media processing
oxipng = "latest" # PNG optimizer
svgo = "latest" # SVG optimizer

[tasks.build]
depends = ["generate/symlinks"]

[tasks.process]
run = [{ task = "optimize" }, { task = "generate/ico" }]

[tasks."generate/ico"]
run = "ffmpeg -y -i exports/favicon-32.png exports/favicon.ico"

[tasks."optimize"]
depends = ["optimize/png", "optimize/svg"]

[tasks."optimize/png"]
run = "oxipng --opt max --scale16 exports/*.png"

[tasks."optimize/svg"]
run = "svgo exports/*.svg --precision 3"

[tasks."generate/symlinks"]
run = '''
#!/usr/bin/env bash

cd ../pkgs/app-website/public/
public_rel="../../../assets/exports"
ln -sf "$public_rel/favicon.ico" favicon.ico
ln -sf "$public_rel/favicon.svg" favicon.svg
ln -sf "$public_rel/icon-180.png" apple-touch-icon.png
ln -sf "$public_rel/icon-192.png" icon-192.png
ln -sf "$public_rel/icon-512.png" icon-512.png
cd -

cd ../pkgs/app-website/src/assets/
assets_rel="../../../../assets/exports"
ln -sf "$assets_rel/logotype.svg" logotype.svg
ln -sf "$assets_rel/logomark.svg" logomark.svg
ln -sf "$assets_rel/icon.svg" icon.svg
ln -sf "$assets_rel/favicon-mono.svg" favicon-mono.svg
cd -
'''

depends = ["process"]
