build:
  cargo run --bin gt -- build .

publish: publish-py publish-ts publish-rs

publish-py:
  cd dist/py && poetry publish --build

publish-ts:
  cd dist/ts && pnpm publish

publish-rs:
  cd dist/rs && cargo publish