name = "genotype-json-types"

[ts]
enabled = true

[ts.manifest]
name = "genotype-json-types"
version = "0.1.0"
description = "Genotype language JSON types"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
files = ["src", "README.md"]

[rs]
enabled = true

[rs.manifest]
[rs.manifest.package]
name = "genotype_json_types"
version = "0.1.0"
edition = "2021"
description = "Genotype language JSON types"
license = "MIT"

[py]
enabled = true
module = "genotype_json_types"
version = "legacy"

[py.manifest]
name = "genotype-json-types"
version = "0.1.0"
description = "Genotype language JSON types"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
readme = "README.md"
