[tasks.preinstall]
description = "Preinstall steps"
depends = ["//pkgs/crate-genotype-formatters-wasm:build", "//pkgs/crate-genotype-wasm:build"]

[tasks.build]
description = "Builds the package"
depends = ["//pkgs/crate-genotype-formatters-wasm:build", "//pkgs/crate-genotype-wasm:build"]

[tasks."build:dev"]
description = "Builds the package for development"
depends = [
  "//pkgs/crate-genotype-formatters-wasm:build:dev",
  "//pkgs/crate-genotype-wasm:build:dev",
]

[tasks."types"]
description = "Checks types"
run = "pnpm exec tsc --build"

[tasks."types:watch"]
description = "Checks types in watch mode"
run = "pnpm exec tsc --build --watch"
