#!/usr/bin/env node

/**
 * The script generates the agent skill files from the website MDX content.
 */

import cp from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import url from "node:url";
import util from "node:util";
import { lit } from "smollit";
import { Mdx } from "../src/index.ts";

const execFile = util.promisify(cp.execFile);

const rootDir = url.fileURLToPath(new URL("../../../", import.meta.url));

export const skillDir = path.join(rootDir, "pkgs/crate-genotype-cli/skill");

const docsDir = path.join(rootDir, "pkgs/app-website/src/content/docs/docs");

export const pages: Mdx.PagesMap = {
  "getting-started/index": "getting-started.md",
  "language/index": "language.md",
  "toolchain/cli": "cli.md",
  "toolchain/configuration": "configuration.md",
  ...Object.fromEntries(
    ["python", "rust", "typescript"].flatMap((target) => [
      [`targets/${target}/index`, `${target}.md`],
      [`targets/${target}/configuration`, `${target}-configuration.md`],
    ]),
  ),
};

if (import.meta.main) {
  const check = process.argv.includes("--check");
  await generateSkill(check);
}

export async function buildOutputs(): Promise<Map<string, string>> {
  const resultEntries = await Promise.all(
    Object.entries(pages).map(async ([page, name]) => {
      const mdxPath = path.join(docsDir, `${page}.mdx`);
      const pagePath = path.join(skillDir, name);

      const mdx = await fs.readFile(mdxPath, "utf8");
      const md = Mdx.render(mdx, pages);

      return [pagePath, md] as const;
    }),
  );
  const result = new Map(resultEntries);
  const allPages = ["SKILL.md", ...Object.values(pages)];

  const filesBundlePath = path.join(skillDir, "../src/commands/skill/files.rs");

  result.set(
    filesBundlePath,
    lit`
      // Generated by pkgs/npm-genotype-skill/src/generate-skill.ts.

      #[rustfmt::skip]
      pub(super) const FILES: &[(&str, &str)] = &[
  ${allPages.map((name) => `      ("${name}", include_str!("../../../skill/${name}")),`).join("\n")}
    ];`,
  );

  return result;
}

export async function generateSkill(check = false): Promise<void> {
  const stale: Record<string, string> = {};

  const outputs = await buildOutputs();

  await Promise.all(
    [...outputs].map(async ([filePath, content]) => {
      if (check) {
        const relPath = path.relative(rootDir, filePath);
        try {
          const curContent = await fs.readFile(filePath, "utf8");
          if (curContent !== content) stale[relPath] = "modified";
        } catch (err) {
          if (err instanceof Error && "code" in err && err.code === "ENOENT") {
            stale[relPath] = "missing";
          } else {
            throw err;
          }
        }
      } else {
        await fs.mkdir(path.dirname(filePath), { recursive: true });
        await fs.writeFile(filePath, content);
      }
    }),
  );

  const staleEntries = Object.entries(stale);
  if (staleEntries.length)
    throw new Error(lit`
      Run \`mise //pkgs/npm-genotype-skill:gen\` to update:

${staleEntries.map(([file, reason]) => `      ${file}: ${reason}`).join("\n")}
    `);

  await execFile("oxfmt", ["**/*.md"], { cwd: skillDir });
}
