[src]
config_hash = "988a9770344c348d"

[src.modules."types/remote.type"]
id = "remote"
hash = "3f01d1e6e6ba20b7"
deps = ["genotype_core", "genotype_project"]

[dist.ts."../npm-genotype-types/src/backend/index.ts"]
hash = "c3537f3f80da094a"

[dist.ts."../npm-genotype-types/src/backend/remote.ts"]
hash = "6eb306f329bcc579"
srcId = "remote"

[dist.rs."src/types/mod.rs"]
hash = "1b2f28d2f7457bed"

[dist.rs."src/types/remote.rs"]
hash = "90fd5eb8352c95ab"
srcId = "remote"
