[src]
config_hash = "2d28c27bda6b7249"

[src.modules."types/meta.type"]
id = "meta"
hash = "56630ec34a014cc1"
deps = []

[src.modules."types/remote.type"]
id = "remote"
hash = "1f79228aed5c165c"
deps = ["meta"]

[dist.ts."../npm-genotype-types/src/compiler/index.ts"]
hash = "820c1c6b77fd5fc4"

[dist.ts."../npm-genotype-types/src/compiler/meta.ts"]
hash = "04c4a714e3803650"
srcId = "meta"

[dist.ts."../npm-genotype-types/src/compiler/remote.ts"]
hash = "440b17c52c57f20a"
srcId = "remote"

[dist.rs."src/types/meta.rs"]
hash = "95be4ced69dbefe7"
srcId = "meta"

[dist.rs."src/types/mod.rs"]
hash = "f9437e0cf46c0791"

[dist.rs."src/types/remote.rs"]
hash = "81d69d3e62683f7f"
srcId = "remote"
