name = "genotype-test-map-key-alias"
dist = "dist/ts-effect"

[build]
file = false

[ts]
enabled = true
mode = "effect"

[ts.manifest]
name = "genotype-test-map-key-alias-effect-types"
version = "0.1.0"
