[package]
name = "genotype_lang_rs_tree"
version = "0.13.0"
edition = "2024"
description = "Genotype language Rust target AST crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dependencies]
genotype_config = { version = "0.13.0", path = "../../../config" }
genotype_lang_core_tree = { version = "0.13.0", path = "../../core/tree" }
genotype_lang_rs_config = { version = "0.13.0", path = "../config" }
genotype_lang_rs_core = { version = "0.13.0", path = "../core" }
genotype_parser = { version = "0.13.0", path = "../../../parser" }
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1.0.64"
heck = "0.5.0"
unicode-xid = "0.2.6"

[dev-dependencies]
pretty_assertions = "1.4.1"
