[package]
name = "genotype_lang_rs_visitor"
version = "0.4.1"
edition = "2021"
description = "Genotype language Rust target visitor crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/genotype"

[dependencies]
genotype_lang_rs_tree = { version = "0.4.1", path = "../tree" }

[dev-dependencies]
pretty_assertions = "1.4.1"
