name = "genotype-test-formatters-formatted"
dist = "./dist/formatted"

[build]
file = false

[ts]
enabled = true
formatters = [{ kind = "oxfmt", args = ["src/index.ts", "src/model.ts"] }]

[rs]
enabled = true
formatters = [{ kind = "cargo", cmd = "fmt", args = ["--all"] }]

[rs.manifest.workspace]

[py]
enabled = true
formatters = [{ kind = "uv", cmd = "ruff", args = ["format"] }]
