build:
  cargo run --bin gt -- build json/tree

publish: publish-py publish-ts publish-rs

publish-py:
  cd libs/py && poetry publish --build

publish-ts:
  cd libs/ts && pnpm publish

publish-rs:
  cd libs/rs && cargo publish