name: Build
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # Linux

          # x86
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cli-name: gt
            lsp-name: gts

          # ARM
          # TODO: Enable when GitHub Actions supports ARM on Linux runners: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
          # - os: <TODO>
          #   target: aarch64-unknown-linux-gnu
          #   cli-name: gt
          #   lsp-name: gts

          # macOS

          # x86
          - os: macos-26-intel
            target: x86_64-apple-darwin
            cli-name: gt
            lsp-name: gts

          # ARM
          - os: macos-26
            target: aarch64-apple-darwin
            cli-name: gt
            lsp-name: gts

          # Windows

          # x86
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cli-name: gt.exe
            lsp-name: gts.exe

          # ARM
          # TODO: Enable when GitHub Actions supports ARM on Linux runners: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
          # - os: <TODO>
          #   target: aarch64-pc-windows-msvc
          #   cli-name: gt.exe
          #   lsp-name: gts.exe

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}

      - name: Set Up Dev Env
        uses: ./.github/actions/setup
        with:
          target-key: build-${{ matrix.target }}

      - name: Add Target
        run: rustup target add ${{ matrix.target }}

      - name: Build CLI
        # TODO: Move to mise task
        run: cargo build --release --package genotype_cli --target ${{ matrix.target }}

      - name: Build LSP
        # TODO: Move to mise task
        run: cargo build --release --package genotype_lsp --target ${{ matrix.target }}

      - name: Save Target Cache
        uses: ./.github/actions/cache-save/target
        with:
          target-key: build-${{ matrix.target }}-${{ github.sha }}

      - name: Upload CLI Binaries
        uses: actions/upload-artifact@v6
        with:
          path: target/${{ matrix.target }}/release/${{ matrix.cli-name }}
          name: ${{ matrix.cli-name }}-${{ matrix.target }}-${{ github.sha }}

      - name: Upload LSP Binaries
        uses: actions/upload-artifact@v6
        with:
          path: target/${{ matrix.target }}/release/${{ matrix.lsp-name }}
          name: ${{ matrix.lsp-name }}-${{ matrix.target }}-${{ github.sha }}
