name: CI

on:
  push:
    branches:
      - main

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set Up Dev Env
        uses: ./.github/actions/setup
        with:
          target-key: qa

      - name: Check Code Formatting
        run: mise :format:check
        # id: format
        # continue-on-error: true

      - name: Lint Code
        run: mise :lint
        # id: lint
        # continue-on-error: true

      - name: Run Unit Tests
        run: mise :test/unit
        # id: test-unit
        # continue-on-error: true

      - name: Run System Tests
        run: mise :test/system
        # id: test-system
        # continue-on-error: true

      - name: Save Cache
        if: always()
        uses: ./.github/actions/cache-save
        with:
          target-key: qa

      # TODO: Re-enable continue-on-error if GitHub ever addresses the problem:
      # - https://github.com/orgs/community/discussions/15452
      # - https://github.com/actions/runner/issues/2347

      # - name: Fail if QA Failed
      #   if: |
      #     steps.format.outcome == 'failure' ||
      #     steps.lint.outcome == 'failure' ||
      #     steps.test-unit.outcome == 'failure' ||
      #     steps.test-system.outcome == 'failure'
      #   run: exit 1

  build:
    name: Build
    needs: qa
    uses: ./.github/workflows/ci-build.yml
    with:
      sha: ${{ github.event.pull_request.head.sha || github.sha }}