name: QA

on:
  workflow_call:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Set Up Dev Env
        uses: ./.github/actions/setup
        # TODO: Enable after adding Oxlint or similar that require Node.js
        # with:
        #   enable-node: true

      - name: Check Code Formatting
        run: mise :format:check

      - name: Lint Code
        run: mise :lint

      - name: Save Cache
        if: always()
        uses: ./.github/actions/cache-save
        with:
          enable-node: true

      - name: Display Stats
        if: always()
        uses: ./.github/actions/stats

  test-unit:
    name: Test Unit
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Set Up Dev Env
        uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: mise :test/unit

      - name: Save Cache
        if: always()
        uses: ./.github/actions/cache-save

      - name: Display Stats
        if: always()
        uses: ./.github/actions/stats

  test-system:
    name: Test System
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Set Up Dev Env
        uses: ./.github/actions/setup

      - name: Run System Tests
        run: mise :test/system

      - name: Save Cache
        if: always()
        uses: ./.github/actions/cache-save

      - name: Display Stats
        if: always()
        uses: ./.github/actions/stats
